# Configuración de despliegue para Render.com
services:
  - type: web
    name: gloobix-io
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PING_INTERVAL
        value: 840000  # 14 minutos en milisegundos
    healthCheckPath: /health
    autoDeploy: true
    branch: main